from __future__ import annotations
from typing import TypedDict, List, Dict, Any, Optional

class AgentState(TypedDict):
    """
    Represents the state of the agentic process.
    """
    messages: List[Dict[str, str]]    # History of messages (user input, system prompts, etc.)
    plan: List[Dict[str, Any]]        # The structured plan (list of steps)
    current_step_index: int           # Index of the step currently being executed
    tool_outputs: Dict[str, Any]      # Storage for outputs generated by tools/steps
    final_response: Optional[str]     # The final response to return to the user
    
    # Memory system fields
    memory_context: Optional[str]     # Injected memory context (NOW + LOG + facts)
    agent_name: Optional[str]         # Which agent is handling this (for memory isolation)
    auto_log_enabled: Optional[bool]  # Auto-log all actions (default: True)
    
    # Agent integration field (NEW)
    agent_instance: Any               # Agent instance with SkillRegistry (typed as Any to avoid runtime eval issues)

    # Intent Classification (Phase 1C)
    intent_type: Optional[str]        # "tool_use", "question", "chat"
    intent_category: Optional[str]    # Detailed category if needed
